// lib/service-content.ts — Rich content for individual service pages

export interface ServiceContent {
  overview: string;
  signs: string[];
  process: { step: string; description: string }[];
  prevention: string[];
  whyPro: string;
}

export const SERVICE_CONTENT: Record<string, ServiceContent> = {
  'ant-control': {
    overview: `Ant infestations are one of the most common household pest problems — and one of the most misunderstood. What starts as a few scouts in your kitchen can quickly become thousands of ants forming trails through your walls, cabinets, and food storage areas. Different species require different treatment approaches: carpenter ants tunnel through wood and cause structural damage, while odorous house ants contaminate food supplies. Professional identification and targeted treatment is the only way to get lasting control.`,
    signs: [
      'Visible ant trails along walls, countertops, or floors',
      'Small piles of sawdust or wood shavings near baseboards (carpenter ants)',
      'Rustling sounds inside walls or woodwork',
      'Winged ants emerging indoors, especially in spring',
      'Ants congregating around pet food, sugar, or grease',
      'Small dirt mounds near your foundation or in your yard',
    ],
    process: [
      { step: 'Inspection', description: 'We identify the ant species, locate nests and entry points, and assess the extent of the infestation throughout your home.' },
      { step: 'Targeted Treatment', description: 'Species-specific baits and professional-grade treatments are applied to eliminate the colony at its source — not just the ants you can see.' },
      { step: 'Entry Point Sealing', description: 'We seal cracks, gaps, and common entry points around your foundation, windows, and utility lines to cut off access.' },
      { step: 'Follow-Up', description: 'A follow-up visit ensures the colony is fully eliminated and your home stays ant-free long-term.' },
    ],
    prevention: [
      'Keep kitchen surfaces clean and free of crumbs and spills',
      'Store food in sealed containers — including pet food',
      'Fix leaky faucets and pipes (ants need water sources)',
      'Seal cracks around windows, doors, and your foundation',
      'Keep tree branches and shrubs trimmed away from your house',
      'Remove woodpiles and debris stored near your foundation',
    ],
    whyPro: `Over-the-counter sprays only kill the ants you can see — they don't reach the colony. A single colony can contain hundreds of thousands of ants, and some species maintain multiple satellite colonies in your walls and yard. Professional treatment targets the queen and the entire colony structure, providing lasting elimination rather than a few days of temporary relief.`,
  },
  'termite-treatment': {
    overview: `Termites cause more property damage in the United States than fires, floods, and storms combined — over $5 billion every year. These silent destroyers can feed on your home's structural wood for years before any visible signs appear. By the time you notice sagging floors or hollow-sounding walls, significant structural damage may have already occurred. In the Northeast, subterranean termites are the primary threat, building mud tubes from the soil to reach the wood in your home. Early detection and professional treatment are critical.`,
    signs: [
      'Mud tubes along your foundation, walls, or support beams',
      'Hollow-sounding wood when tapped',
      'Bubbling or peeling paint that resembles water damage',
      'Discarded wings near windows, doors, or light fixtures',
      'Tight-fitting doors and windows (termite damage warps frames)',
      'Frass — small, dark pellets near wood surfaces (drywood termites)',
    ],
    process: [
      { step: 'Comprehensive Inspection', description: 'We thoroughly inspect your foundation, crawl spaces, attic, and all wood structures to identify termite species, entry points, and damage extent.' },
      { step: 'Custom Treatment Plan', description: 'Based on the inspection, we design a targeted approach using liquid soil barriers, bait stations, or a combination for maximum protection.' },
      { step: 'Professional Treatment', description: 'Licensed technicians apply treatment to eliminate the active colony and create a continuous protective barrier around your entire home.' },
      { step: 'Monitoring & Protection', description: 'Ongoing monitoring ensures termites stay gone. We stand behind our work with a satisfaction guarantee.' },
    ],
    prevention: [
      'Eliminate any wood-to-soil contact around your home\'s foundation',
      'Fix leaks promptly — termites thrive in moist environments',
      'Ensure proper drainage directs water away from your foundation',
      'Keep gutters clean and downspouts pointed away from your home',
      'Store firewood at least 20 feet from your house and elevated off the ground',
      'Schedule annual termite inspections — early detection saves thousands in repairs',
    ],
    whyPro: `Termite treatment requires specialized equipment, commercial-grade products, and expert knowledge of termite biology and behavior. Consumer products cannot reach deep into soil or wall voids where colonies live. Professional treatment creates a continuous protective barrier around your entire home, and our licensed technicians know exactly where to look for hidden damage that homeowners almost always miss.`,
  },
  'bed-bug-removal': {
    overview: `Bed bugs are expert hitchhikers that can infest even the cleanest homes. They travel on luggage, clothing, and secondhand furniture, hiding in mattress seams, furniture joints, electrical outlets, and behind baseboards. At night, they emerge to feed on sleeping hosts. A single female can lay up to 500 eggs in her lifetime, meaning a minor problem can become a full-blown infestation within weeks. Bed bugs have developed resistance to many over-the-counter treatments, making professional intervention essential for elimination.`,
    signs: [
      'Small, itchy red welts appearing in lines or clusters on your skin',
      'Tiny blood spots on your sheets or pillowcases',
      'Dark spots (bed bug excrement) on mattress seams and bedding',
      'A sweet, musty odor in heavily infested rooms',
      'Live bugs or translucent shed skins in mattress seams, furniture joints, or crevices',
      'Bite marks appearing after sleeping — commonly on arms, shoulders, and neck',
    ],
    process: [
      { step: 'Thorough Inspection', description: 'We inspect every room, carefully checking mattresses, furniture, baseboards, and all common hiding spots to map the full scope of infestation.' },
      { step: 'Preparation Guidance', description: 'We provide clear, simple instructions to prepare your home for treatment — maximizing effectiveness while minimizing hassle.' },
      { step: 'Multi-Method Treatment', description: 'We use a combination of professional-grade methods targeting bed bugs at every life stage — eggs, nymphs, and adults — in all hiding spots.' },
      { step: 'Follow-Up Verification', description: 'A follow-up visit ensures complete elimination, including any bed bugs that hatched after the initial treatment.' },
    ],
    prevention: [
      'Inspect hotel rooms carefully and keep luggage on hard surfaces when traveling',
      'Use protective encasements on mattresses and box springs',
      'Inspect secondhand furniture thoroughly before bringing it inside your home',
      'Reduce clutter — especially around beds — to minimize hiding spots',
      'Vacuum regularly around beds, nightstands, and upholstered furniture',
      'Wash and dry bedding on high heat weekly',
    ],
    whyPro: `Bed bugs are among the most difficult pests to eliminate without professional help. They're resistant to many consumer pesticides, can survive months without a blood meal, and hide in cracks thinner than a credit card. Professional treatment uses specialized methods that penetrate deep into every hiding spot and target all life stages — eggs, nymphs, and adults — ensuring complete elimination that DIY methods simply can't achieve.`,
  },
  'rodent-control': {
    overview: `Mice and rats are far more than a nuisance — they pose serious health risks and cause significant property damage. Rodents contaminate food with droppings and urine, spread diseases including hantavirus and salmonella, and their constant gnawing damages electrical wiring (a leading cause of house fires), plumbing, insulation, and structural elements. A single pair of mice can produce up to 60 offspring per year, so by the time you spot one mouse, there are likely many more hiding in your walls.`,
    signs: [
      'Droppings along walls, inside cabinets, or near food sources',
      'Gnaw marks on food packaging, wires, wood, or drywall',
      'Scratching or scurrying sounds in walls or ceilings, especially at night',
      'Nests made from shredded paper, fabric, or insulation in hidden areas',
      'Grease marks (rub marks) along walls and baseboards from repeated travel',
      'An ammonia-like smell from rodent urine, especially in enclosed spaces',
    ],
    process: [
      { step: 'Inspection & Assessment', description: 'We identify all entry points, nesting areas, and travel routes through a thorough inspection of your home\'s interior and exterior.' },
      { step: 'Exclusion', description: 'We seal every gap, crack, and hole — mice can squeeze through openings as small as a dime, rats through a quarter-sized gap.' },
      { step: 'Trapping & Removal', description: 'Strategic placement of professional traps along travel routes eliminates the existing population quickly and humanely.' },
      { step: 'Sanitation & Prevention', description: 'We clean affected areas, remove nesting materials, and provide specific recommendations to keep rodents from returning.' },
    ],
    prevention: [
      'Seal all gaps larger than ¼ inch around your foundation, doors, and utility lines',
      'Store food in glass or metal containers with tight-fitting lids',
      'Keep garbage in sealed bins and remove trash regularly',
      'Trim vegetation and tree branches away from your home\'s exterior',
      'Eliminate standing water and fix leaky pipes or faucets',
      'Store firewood at least 20 feet from your home and elevated off the ground',
    ],
    whyPro: `Rodents are intelligent and cautious — they quickly learn to avoid poorly placed traps and are unaffected by most consumer-grade products. Professional rodent control combines three critical elements: exclusion (permanently sealing every entry point), strategic trapping to eliminate existing populations, and ongoing monitoring to ensure they don't return. We also address the sanitation and structural issues that DIY approaches typically miss.`,
  },
  'cockroach-control': {
    overview: `Cockroaches are among the most resilient pests on the planet, having survived for over 300 million years. They breed rapidly — a single German cockroach can produce up to 400 offspring in a year. Beyond being unsettling, cockroaches are a real health threat: they trigger asthma and allergies (especially in children), spread bacteria like E. coli and salmonella, and contaminate food and kitchen surfaces. Their ability to hide in impossibly tiny crevices and rapidly develop resistance to store-bought pesticides makes professional treatment essential.`,
    signs: [
      'Live roaches scurrying when you turn on lights in kitchens or bathrooms',
      'Droppings that look like coffee grounds or black pepper',
      'Egg cases (oothecae) — dark brown, capsule-shaped casings in hidden areas',
      'A musty, oily odor in areas with heavy activity',
      'Smear marks along walls and surfaces where roaches travel regularly',
      'Shed skins from growing nymphs found behind appliances and in cabinets',
    ],
    process: [
      { step: 'Species Identification', description: 'We identify the cockroach species — German, American, and Oriental roaches each require different treatment strategies for effective control.' },
      { step: 'Targeted Treatment', description: 'Professional-grade gel baits, residual treatments, and insect growth regulators target roaches where they actually live and breed.' },
      { step: 'Harborage Elimination', description: 'We treat every crack, crevice, void, and harborage area to reach the hidden populations that you never see.' },
      { step: 'Monitoring & Follow-Up', description: 'Sticky monitors and follow-up treatments verify elimination and prevent re-infestation.' },
    ],
    prevention: [
      'Keep kitchens and bathrooms clean and dry at all times',
      'Fix leaky pipes and faucets — cockroaches need moisture to survive',
      'Store all food in sealed containers and never leave pet food out overnight',
      'Take garbage out regularly and use trash bins with tight-fitting lids',
      'Seal cracks around pipes, behind cabinets, and along baseboards',
      'Eliminate clutter, especially cardboard boxes and paper bags where roaches harbor',
    ],
    whyPro: `For every cockroach you see, dozens more are hiding in your walls, behind appliances, and inside plumbing voids. Store-bought sprays and foggers scatter roaches to new hiding spots without eliminating the colony. Professional treatment uses a strategic combination of commercial-grade baits, long-lasting residual products, and insect growth regulators that work together to eliminate the entire population — including the eggs you can't see.`,
  },
  'mosquito-control': {
    overview: `Mosquitoes aren't just a summer annoyance — they're considered the most dangerous animals on Earth due to their ability to transmit serious diseases. In the Northeast, West Nile virus, Eastern Equine Encephalitis (EEE), and Zika are all concerns. Mosquito season typically runs from April through October, with peak activity during the warm, humid summer months. Standing water as shallow as a bottle cap can breed hundreds of mosquitoes. A professional mosquito program lets your family actually enjoy your yard all season long.`,
    signs: [
      'Frequent mosquito bites when spending time outdoors, especially at dawn and dusk',
      'Persistent buzzing in shaded, damp areas of your yard',
      'Standing water collecting in gutters, planters, toys, tarps, or birdbaths',
      'Large swarms of mosquitoes in shaded areas near vegetation',
      'Mosquito larvae — small wriggling organisms visible in any stagnant water',
    ],
    process: [
      { step: 'Property Assessment', description: 'We survey your entire property to identify breeding sites, resting areas, and the conditions driving mosquito activity.' },
      { step: 'Source Reduction', description: 'We eliminate or treat standing water sources where mosquitoes breed — stopping the problem at its source is the most effective first step.' },
      { step: 'Barrier Treatment', description: 'Professional barrier sprays are applied to vegetation, fences, and structures where adult mosquitoes rest, providing weeks of protection.' },
      { step: 'Seasonal Program', description: 'Regular treatments throughout mosquito season keep populations suppressed so your family can enjoy your outdoor spaces worry-free.' },
    ],
    prevention: [
      'Empty all standing water from flowerpots, buckets, gutters, and toys weekly',
      'Keep gutters clean and flowing freely',
      'Change birdbath water at least twice a week',
      'Maintain swimming pools with proper chemical balance and filtration',
      'Trim overgrown vegetation where mosquitoes rest during the day',
      'Repair or replace torn window and door screens',
    ],
    whyPro: `Consumer mosquito sprays and citronella candles only provide temporary personal protection — they don't reduce the mosquito population breeding in your yard. Professional barrier treatments target mosquitoes where they rest and reproduce, dramatically cutting populations for weeks at a time. A seasonal program provides consistent, reliable protection throughout the entire mosquito season without the hassle of reapplying products yourself.`,
  },
  'spider-control': {
    overview: `While most spiders in the Northeast are harmless, their webs and unexpected appearances can make your home feel uncomfortable — and some species can deliver painful bites. More importantly, spiders are predators that follow their food source, so a spider problem in your home usually signals an underlying insect infestation. Professional spider control addresses both the spiders and the insects attracting them, giving you comprehensive protection and a home that actually feels clean.`,
    signs: [
      'Webs appearing regularly in corners, basements, garages, and around exterior lights',
      'Frequent spider sightings indoors, especially in dark, undisturbed areas',
      'Egg sacs attached to webs or tucked into crevices and corners',
      'An abundance of other insects in your home (spiders go where the food is)',
      'Bites appearing as red, swollen welts — typically from accidental contact while sleeping or reaching into storage',
    ],
    process: [
      { step: 'Inspection', description: 'We identify spider species present, locate nesting and webbing areas, and assess what insect prey is attracting them to your home.' },
      { step: 'Web & Nest Removal', description: 'We physically remove all visible webs, egg sacs, and nesting materials from your home\'s interior and exterior.' },
      { step: 'Perimeter Treatment', description: 'Professional treatments are applied around your foundation, all entry points, and key harborage areas inside and out.' },
      { step: 'Prey Reduction', description: 'By treating the insects that spiders feed on, we eliminate their food source and their reason to stay in your home.' },
    ],
    prevention: [
      'Reduce outdoor lighting or switch to yellow/sodium vapor bulbs that attract fewer insects',
      'Keep firewood, rock piles, and yard debris away from your home\'s foundation',
      'Seal gaps around windows, doors, and utility entry points',
      'Reduce clutter in basements, garages, and storage areas',
      'Dust and vacuum corners, closets, and under furniture regularly',
      'Trim vegetation and landscaping back from your home\'s exterior walls',
    ],
    whyPro: `Spiders are uniquely difficult to control with store-bought sprays because they don't groom themselves like other insects — they walk right over most surface treatments without being affected. Professional spider control takes a multi-pronged approach: direct treatment of spiders and their hiding spots, elimination of the insect prey drawing them in, and long-lasting perimeter barriers that prevent new spiders from entering your home.`,
  },
  'wasp-hornet-removal': {
    overview: `Wasps and hornets can turn your backyard into a danger zone, especially for family members with allergies — a single sting can trigger a life-threatening anaphylactic reaction. Unlike honeybees, wasps and hornets can sting repeatedly. They build nests in eaves, soffits, wall voids, tree branches, and underground burrows, and colonies grow increasingly aggressive as they expand through the summer months. Attempting to remove a nest without professional equipment risks provoking a swarm attack that can result in dozens of stings.`,
    signs: [
      'Visible paper nests under eaves, in bushes, trees, or hanging from structures',
      'Wasps or hornets flying in a consistent pattern to and from a fixed point on your property',
      'Increased wasp activity around outdoor eating areas, garbage, or sweet drinks',
      'Buzzing sounds from inside walls, attics, or soffits',
      'Chewed wood or papery nest material near eaves and overhangs',
      'Aggressive insect behavior when you approach certain areas of your yard or home',
    ],
    process: [
      { step: 'Nest Location', description: 'We locate all active nests on your property, including hidden nests inside wall voids, attics, and underground burrows that aren\'t visible.' },
      { step: 'Safe Elimination', description: 'Using professional protective equipment and targeted products, we eliminate the colony and safely remove or treat the nest.' },
      { step: 'Entry Point Treatment', description: 'We treat entry points and areas where wasps commonly build to discourage new colonies from establishing.' },
      { step: 'Prevention Plan', description: 'We identify conditions attracting wasps to your property and recommend changes to minimize future nesting activity.' },
    ],
    prevention: [
      'Inspect eaves, soffits, and overhangs in early spring — catch new nests while they\'re small',
      'Seal gaps and cracks in your home\'s exterior, especially around the roofline and soffits',
      'Keep outdoor garbage cans tightly sealed at all times',
      'Avoid leaving sugary drinks, ripe fruit, or food uncovered outdoors',
      'Treat or paint exposed wood surfaces that paper wasps harvest for nest building',
      'Consider preventive treatments in early spring before colonies have a chance to establish',
    ],
    whyPro: `Removing a wasp or hornet nest yourself is genuinely dangerous. Disturbing a nest can trigger a coordinated attack from hundreds of stinging insects, and underground nests are especially unpredictable. Professional technicians have the protective equipment, commercial-grade products, and training to safely eliminate colonies — including nests hidden deep in wall voids, attics, or underground that are impossible to reach with consumer products.`,
  },
  'flea-tick-treatment': {
    overview: `Fleas and ticks aren't just a problem for your pets — they bite humans and can transmit serious diseases. Ticks in the Northeast carry Lyme disease, anaplasmosis, and babesiosis, all of which are increasingly common. Fleas can infest your entire home, laying eggs deep in carpets, upholstered furniture, and pet bedding. A single flea lays up to 50 eggs per day, and pupae can lie dormant for months waiting for a host. Effective control means treating your home, your yard, and breaking the reproductive cycle at every stage.`,
    signs: [
      'Pets scratching, biting, or licking themselves excessively',
      'Small, dark insects jumping on furniture, carpets, or your skin',
      'Flea dirt (tiny black specks that turn red when wet) in pet bedding or on your pet\'s coat',
      'Red, itchy bite marks on ankles, legs, or around the waistline',
      'Ticks found attached to family members or pets after time outdoors',
      'Hair loss or hot spots on pets from excessive scratching and irritation',
    ],
    process: [
      { step: 'Home & Yard Assessment', description: 'We inspect both indoor and outdoor areas to identify flea and tick hotspots, severity, and the conditions supporting them.' },
      { step: 'Indoor Treatment', description: 'Professional treatments target adult fleas, larvae, and eggs in carpets, upholstery, pet areas, crevices, and throughout your home.' },
      { step: 'Yard Treatment', description: 'We treat shaded areas, tall grass, leaf litter, and landscape features where ticks and fleas thrive in your yard.' },
      { step: 'Lifecycle Disruption', description: 'Insect growth regulators prevent eggs and larvae from maturing into biting adults, breaking the reproduction cycle for lasting control.' },
    ],
    prevention: [
      'Keep pets on year-round flea and tick prevention as recommended by your veterinarian',
      'Vacuum carpets, rugs, and upholstered furniture frequently — and empty the vacuum outside',
      'Wash all pet bedding in hot water at least once a week',
      'Keep your lawn mowed short and remove leaf litter regularly',
      'Create a gravel or wood chip barrier between your lawn and adjacent wooded areas',
      'Check all family members and pets for ticks after spending time outdoors',
    ],
    whyPro: `Only about 5% of a flea infestation consists of visible adult fleas — the other 95% are eggs, larvae, and pupae hiding deep in your carpets and furniture. Store-bought foggers and sprays miss these hidden life stages completely, which is why the problem always comes back. Professional treatment uses a combination of fast-acting adulticides and insect growth regulators that target every stage of the flea lifecycle, plus yard treatments to eliminate the outdoor breeding source.`,
  },
  'wildlife-removal': {
    overview: `Raccoons, squirrels, opossums, skunks, and other wildlife can cause serious damage when they decide your home makes a good den. They tear through insulation, chew electrical wiring (creating fire hazards), contaminate attics and crawl spaces with droppings and urine, and can introduce parasites like fleas, ticks, and mites. Beyond property damage, wildlife can carry rabies and other zoonotic diseases. Professional, humane removal is the safest and most effective approach — and in New York, it's required by law for most species.`,
    signs: [
      'Scratching, thumping, or scurrying sounds in your attic, walls, or chimney — especially at dawn and dusk',
      'Droppings, urine stains, or strong odors in your attic, garage, or crawl space',
      'Damaged soffits, vents, fascia boards, or roof shingles',
      'Chewed wiring, torn insulation, or damaged ductwork',
      'Torn garbage bags, overturned trash cans, or scattered debris',
      'Visible entry holes or damage around your roofline, foundation, or chimney',
    ],
    process: [
      { step: 'Inspection & Identification', description: 'We identify the animal species, locate all entry points, and assess any damage to your home\'s structure, insulation, and wiring.' },
      { step: 'Humane Removal', description: 'Using humane traps and one-way exclusion devices, we safely remove wildlife from your home in full compliance with state regulations.' },
      { step: 'Permanent Exclusion', description: 'We seal every entry point with professional-grade, animal-resistant materials to ensure wildlife cannot re-enter.' },
      { step: 'Cleanup & Restoration', description: 'We clean and sanitize contaminated areas, remove soiled insulation, and repair or recommend repairs for any structural damage.' },
    ],
    prevention: [
      'Inspect your roofline, soffits, and vents regularly for gaps or damage',
      'Install chimney caps and heavy-duty vent covers',
      'Trim tree branches that overhang or touch your roof',
      'Secure garbage cans with locking or animal-proof lids',
      'Never leave pet food or birdseed outside overnight',
      'Seal foundation gaps, crawl space openings, and gaps around utility lines',
    ],
    whyPro: `Wildlife removal requires knowledge of animal behavior, proper trapping and exclusion techniques, and full awareness of state and local wildlife regulations. In New York, many species are legally protected, and improper removal can result in fines. Professional wildlife control ensures animals are removed humanely and legally, all entry points are permanently sealed with the right materials, and contaminated areas are properly sanitized to protect your family's health.`,
  },
  'commercial-pest-control': {
    overview: `Pests in a commercial setting don't just cause property damage — they can shut down your business, trigger health code violations, and destroy the reputation you've spent years building. Whether you manage a restaurant, medical office, retail store, warehouse, school, or multi-family property, you need a pest management program that works around your schedule and protects your customers, tenants, and employees. We design customized Integrated Pest Management (IPM) programs tailored to your specific industry, facility, and compliance requirements.`,
    signs: [
      'Customer, tenant, or employee complaints about pest sightings',
      'Droppings, gnaw marks, or grease trails in storage, kitchen, or food prep areas',
      'Health or building inspection violations or warnings',
      'Damaged inventory, product packaging, or stored supplies',
      'Pest activity around dumpsters, loading docks, delivery areas, or entry points',
      'Unusual odors that may indicate hidden rodent or insect infestations',
    ],
    process: [
      { step: 'Facility Assessment', description: 'We conduct a thorough assessment of your entire facility — identifying current pest issues, high-risk areas, and structural vulnerabilities.' },
      { step: 'Custom IPM Program', description: 'We design an Integrated Pest Management program specific to your industry, facility layout, and any regulatory or compliance requirements.' },
      { step: 'Scheduled Service', description: 'Regular service visits are scheduled around your business hours to provide consistent protection with zero disruption to your operations.' },
      { step: 'Documentation & Compliance', description: 'We provide detailed service reports, treatment logs, and compliance documentation to support health inspections and audits.' },
    ],
    prevention: [
      'Maintain strict cleanliness standards in break rooms, kitchens, and food storage areas',
      'Implement proper waste management procedures and keep dumpster areas clean',
      'Seal all cracks and gaps around doors, windows, utility penetrations, and loading docks',
      'Ensure proper drainage throughout the facility and eliminate any standing water',
      'Train staff to identify and immediately report any pest sightings',
      'Schedule regular professional inspections to catch emerging issues before they become problems',
    ],
    whyPro: `Commercial pest control is fundamentally different from residential service — the stakes are higher, the regulations stricter, and the consequences of failure more severe. Our commercial programs use Integrated Pest Management (IPM) principles that emphasize prevention, monitoring, and targeted treatment to protect your business while minimizing chemical exposure. We work discreetly around your schedule and provide complete documentation for every visit.`,
  },

  'raccoon-removal': {
    overview: 'Raccoons are among the most intelligent and adaptable wildlife species invading Camden County homes and businesses. These nocturnal mammals weigh between 10 and 30 pounds and possess remarkable dexterity — their front paws can open latches, tear through soffit material, and pry apart roofing shingles to gain entry to your attic. In Camden County, raccoon activity peaks from late winter through early summer as females seek warm, sheltered spaces to birth and raise their young. Neighborhoods bordering Cooper River Park, the wooded corridors of Winslow Township, and the older tree-lined streets of Haddonfield and Collingswood see especially high raccoon pressure. Once inside, raccoons create latrines that harbor raccoon roundworm (Baylisascaris procyonis), a parasite dangerous to humans and pets. They also damage insulation, ductwork, and electrical wiring, creating fire hazards and driving up energy costs. Our Camden County raccoon removal team holds all required NJDEP wildlife control permits and follows humane live-trapping protocols. We do not just remove the animal — we identify every entry point, install heavy-gauge exclusion materials, and sanitize contaminated areas so your home is safe and secure long after the raccoon is gone.',
    signs: [
      'Heavy thumping or walking sounds in the attic, especially at night',
      'Torn or displaced soffit panels, roof vents, or fascia boards',
      'Dark, cylindrical droppings in piles (raccoon latrines) in the attic or on the roof',
      'Smudge marks and greasy rub marks around roof edges and gutters',
      'Overturned trash cans with bags torn open and food scattered',
      'Damage to garden beds, fish ponds, or pet food left outdoors',
      'Chattering, purring, or growling sounds coming from walls or ceilings',
      'Strong ammonia-like odor from accumulated urine in attic insulation',
    ],
    process: [
      { step: 'Inspection', description: 'Complete exterior and attic inspection to locate all entry and exit points, assess damage, and check for juvenile raccoons.' },
      { step: 'Humane Trapping', description: 'Strategic placement of humane live traps near active entry points, baited and monitored daily in compliance with NJDEP regulations.' },
      { step: 'Exclusion & Sealing', description: 'Once all raccoons are removed, sealing every entry point with commercial-grade galvanized steel mesh, metal flashing, and construction-grade sealants.' },
      { step: 'Sanitation', description: 'Full attic sanitation including removal of contaminated insulation, enzyme-based disinfection of raccoon latrines, and deodorization to eliminate pheromone trails that attract new wildlife.' },
    ],
    prevention: [
      'Secure trash cans with locking lids or bungee cords and store them in a garage until collection day',
      'Trim tree branches at least 8 feet away from your roofline to eliminate aerial access routes',
      'Install chimney caps and heavy-duty vent covers rated for wildlife exclusion',
      'Remove outdoor pet food and bird feeders before dusk when raccoons become active',
      'Repair any damaged soffit, fascia, or roof shingles immediately — even small gaps invite exploration',
      'Install motion-activated lights or sprinklers around the perimeter of your home',
      'Close and lock pet doors at night, as raccoons quickly learn to use them',
    ],
    whyPro: 'Raccoon removal requires NJDEP licensing, proper handling of potentially rabid animals, and thorough decontamination of hazardous raccoon latrines. DIY attempts often result in orphaned juveniles dying inside your walls, creating a far worse problem. Our licensed Camden County wildlife technicians handle every step safely and legally.',
  },
  'squirrel-removal': {
    overview: 'Eastern gray squirrels and southern flying squirrels are the two species most commonly found invading Camden County homes. Gray squirrels are daytime intruders — you will hear them scurrying through your attic at dawn and dusk — while flying squirrels are nocturnal and often go undetected for months. Both species cause serious structural damage by gnawing on electrical wiring, PVC plumbing, wooden joists, and insulation. In fact, squirrel-damaged wiring is a leading cause of unexplained house fires in New Jersey. Cherry Hill, Voorhees, and Mount Laurel — communities with mature oak and maple canopies — experience the highest squirrel intrusion rates in Camden County. Haddonfield\'s historic homes, many built before 1920, are especially vulnerable because aging construction materials offer dozens of potential entry points around soffits, gable vents, and roofline intersections. Squirrels can squeeze through gaps as small as 1.5 inches and will enlarge existing openings by chewing. Our Camden County squirrel removal program uses one-way exclusion doors that allow squirrels to leave naturally without the stress of trapping, combined with comprehensive sealing of every gap, crack, and vulnerability on your home\'s exterior.',
    signs: [
      'Rapid scurrying, scratching, or rolling sounds in the attic during early morning and late afternoon hours',
      'Chew marks on fascia boards, wooden trim, or the edges of gable vents and roof returns',
      'Small, oval-shaped droppings (similar to dark grains of rice) scattered in the attic',
      'Shredded insulation, cardboard, or fabric used as nesting material',
      'Visible entry holes (1.5 inches or larger) along the roofline, at soffit-fascia junctions, or around plumbing penetrations',
      'Chewed or frayed electrical wiring visible in the attic — a serious fire hazard',
      'Squirrels observed repeatedly climbing the same tree or utility line toward your roof',
      'Acorn shells, nut caches, or leaf debris found in attic corners',
    ],
    process: [
      { step: 'Full Inspection', description: 'Thorough inspection of the entire roofline, soffits, gable vents, ridge vents, and plumbing/electrical penetrations to map all current and potential entry points.' },
      { step: 'One-Way Exclusion', description: 'Installation of one-way exclusion devices at primary entry points, allowing squirrels to exit but preventing re-entry — a humane, stress-free method.' },
      { step: 'Sealing', description: 'Complete sealing of all secondary entry points and vulnerabilities using galvanized steel mesh, metal flashing, and chew-proof materials.' },
      { step: 'Follow-Up', description: 'Follow-up inspection within 7–10 days to confirm all squirrels have vacated, remove exclusion devices, and permanently seal the final openings.' },
    ],
    prevention: [
      'Trim all tree branches so they end at least 6–8 feet from your roofline, walls, and utility lines',
      'Install metal collars or baffles around utility poles and trees adjacent to your home',
      'Replace plastic gable vents and ridge vents with metal versions rated for wildlife exclusion',
      'Seal gaps around plumbing stacks, HVAC lines, and electrical conduit where they penetrate the roof or walls',
      'Keep bird feeders at least 15 feet from the house and use squirrel-proof feeder designs',
      'Inspect your roofline and soffits every spring and fall for new gaps or chew damage',
      'Store firewood at least 20 feet from your home\'s foundation to reduce nearby squirrel habitat',
    ],
    whyPro: 'Squirrel exclusion requires working at roof height, identifying every potential entry point (there are often more than homeowners realize), and using materials squirrels cannot chew through. Improper exclusion can trap squirrels inside, leading to frantic chewing, additional damage, and animals dying in wall voids. Our Camden County technicians have the experience and equipment to do it right the first time.',
  },
  'bat-removal': {
    overview: 'Camden County is home to several bat species, with the big brown bat and little brown bat being the most common attic invaders. Bats are beneficial insect predators — a single bat can eat over 1,000 mosquitoes per night — but when they colonize your home, they create serious health and property concerns. Bat guano accumulates rapidly in attic spaces, producing a strong ammonia odor and fostering the growth of Histoplasma capsulatum, the fungus responsible for histoplasmosis, a potentially serious respiratory infection. Bats in Camden County are particularly active near wooded areas and waterways: Gloucester Township, Winslow Township, Clementon, and neighborhoods bordering the Pine Barrens corridor see the highest bat activity. Bats can enter through gaps as small as 3/8 of an inch. It is critical to understand that bats are protected wildlife in New Jersey — the NJDEP prohibits exclusion during the maternity season (approximately May 1 through August 31). Our Camden County bat removal specialists are fully licensed and perform all exclusion work within the legal windows.',
    signs: [
      'Small, dark droppings accumulating below entry points, on windowsills, or in attic spaces — bat guano crumbles easily and contains shiny insect fragments',
      'Strong musty or ammonia-like odor emanating from the attic, walls, or around the roofline',
      'Bats observed flying out from under eaves, soffits, or ridge vents at dusk',
      'Brown or dark staining from body oils around small gaps or cracks on the exterior',
      'Squeaking, scratching, or fluttering sounds inside walls or ceilings, especially at dawn and dusk',
      'A single bat found flying inside your living space — often a sign of a larger colony in the attic',
      'Dead bats found in window wells, on porches, or in the yard',
    ],
    process: [
      { step: 'Observation & Inspection', description: 'Comprehensive dusk observation (bat watch) and interior/exterior inspection to identify the species, estimate colony size, and locate every entry and exit point.' },
      { step: 'Exclusion Valves', description: 'Installation of one-way bat exclusion valves at all active exit points — bats leave naturally at dusk and cannot return, avoiding any direct handling.' },
      { step: 'Complete Sealing', description: 'Sealing of every secondary gap, crack, and construction joint using caulk, expanding foam, steel mesh, and flashing — bats exploit openings as small as 3/8 inch.' },
      { step: 'Guano Cleanup', description: 'Post-exclusion guano removal, attic sanitation with antimicrobial treatment, and insulation replacement if contamination is extensive — performed with full respiratory protection.' },
    ],
    prevention: [
      'Inspect your roofline, soffits, ridge vents, and chimney flashing every spring for new gaps',
      'Install a quality chimney cap with fine mesh screening to prevent bat entry',
      'Seal gaps around plumbing vents, HVAC penetrations, and electrical conduit',
      'Repair or replace damaged window screens, especially in attic gable windows',
      'Ensure attic vent covers have mesh with openings no larger than 1/4 inch',
      'Address any exterior wood rot promptly, as deteriorating wood creates new entry points',
      'Consider installing a bat house on your property at least 20 feet from your home for alternative roosting',
    ],
    whyPro: 'Bat removal in New Jersey must comply with strict NJDEP regulations protecting bat species. Performing exclusion during the maternity season is illegal and can result in significant fines. Additionally, direct contact with bats poses rabies risk, and guano cleanup requires proper respiratory protection. Our licensed Camden County bat specialists ensure full legal compliance, safe exclusion, and thorough decontamination.',
  },
  'bird-control': {
    overview: 'Pest birds — particularly pigeons, European starlings, house sparrows, and Canada geese — cause millions of dollars in property damage across Camden County every year. Pigeon droppings are highly acidic and corrode roofing materials, HVAC equipment, signage, and painted surfaces. Starlings and sparrows nest in vents, soffits, and warehouse rafters, blocking airflow and creating fire hazards. Canada geese foul lawns, sports fields, and commercial landscapes with large volumes of droppings. Camden County\'s mix of urban commercial corridors (Pennsauken, Bellmawr, Runnemede), suburban shopping centers (Cherry Hill, Voorhees), and open spaces near the Delaware River and Cooper River make it especially attractive to pest birds. Our bird control programs include professional installation of bird netting, spike strips, electric shock track systems, and visual and auditory deterrents — all compliant with the federal Migratory Bird Treaty Act.',
    signs: [
      'Large accumulations of bird droppings on ledges, rooftops, sidewalks, loading docks, or HVAC equipment',
      'Nesting material visible in vents, signage, light fixtures, or structural openings',
      'Persistent cooing, chirping, or squawking concentrated around specific areas',
      'Clogged gutters and downspouts caused by feathers and nesting debris',
      'Bird droppings on inventory, products, or equipment inside a warehouse',
      'Foul odors from accumulated droppings or decomposing nesting material',
      'Birds entering the building through loading dock doors or ventilation openings',
      'Aggressive goose behavior on commercial lawns during nesting season',
    ],
    process: [
      { step: 'Site Survey', description: 'Identify the bird species, nesting and roosting locations, flight patterns, entry points, and the extent of contamination.' },
      { step: 'Custom Deterrent Plan', description: 'Design a customized bird deterrent plan using the most effective combination of physical exclusion (netting, spikes, shock track), visual deterrents, and habitat modification.' },
      { step: 'Professional Installation', description: 'Installation of all deterrent systems by trained technicians with aerial lift and fall protection equipment, ensuring full coverage.' },
      { step: 'Cleanup & Monitoring', description: 'Thorough cleanup of all droppings, nesting material, and debris with antimicrobial treatment, followed by ongoing monitoring and maintenance.' },
    ],
    prevention: [
      'Eliminate food sources by securing dumpsters, cleaning loading docks, and removing standing water',
      'Install door strip curtains on warehouse loading docks to prevent birds from entering',
      'Seal all exterior gaps, broken windows, and ventilation openings larger than 3/4 inch',
      'Maintain bird deterrent systems on an annual basis',
      'For goose problems, modify landscaping with tall native plantings along water edges',
      'Remove old nests promptly outside of protected nesting periods',
      'Consider ongoing bird management contracts for commercial properties',
    ],
    whyPro: 'Effective bird control requires species identification, knowledge of federal migratory bird laws, and experience with commercial-grade deterrent systems installed at height. Improper deterrent placement wastes money and fails to solve the problem. Our Camden County bird control technicians design and install proven systems backed by warranties, ensuring long-term results.',
  },
};
